# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b78b21ba3d82e06ededcc58f514ec1906222f3cb749131893c034467fa5b6de4e5b98b2f0db066274a126b61a407f85841183a27e032817ac26bc89c032e100

test:
  secret_key_base: 013aef3408e82741cdeb6d57c72718b61e2a63fc24d1bffadde6afff7fa17a1978a8982da405d01043d196f4997dfcfb0dca6ee2ae87c6d2dce1b37cd5f7058e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
